# docker-compose file setting up environment for terraform with other tools

version: '3.8'
services:
    
    terraform-container:
        image: esteveslima/terraform-template-image:latest           
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/terraform-template                                    # Hosting the project folder as volume
            - ./config/aws/.aws:/root/.aws                              # Setting up AWS credentials inside the container(~/.aws)
        working_dir: /terraform-template
        restart: "no"