# Optional docker environment for terraform with other tools

version: '3.8'
services:
    
    terraform-container:
        image: esteveslima/terraform-template-image:latest           
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/terraform-template                                    # Hosting the project folder as volume
            - ./config/aws/.aws:/root/.aws                              # Setting up AWS credentials inside the container(~/.aws)
            - /var/run/docker.sock:/var/run/docker.sock                 # Bind host docker socket to the container(enable docker commands to host machine)
        working_dir: /terraform-template
        restart: "no"